routes/web.php
    Route::get('/packages/create', 'PricingListsControllers\PackageController@create')->middleware(["permission:packages screen"])->name('packages.create');
    Route::post('/packages/store', 'PricingListsControllers\PackageController@store')->middleware(["permission:packages screen"])->name('packages.store');
    Route::get('/packages/edit/{id}', 'PricingListsControllers\PackageController@edit')->middleware(["permission:packages screen"]);
    Route::post('/packages/update', 'PricingListsControllers\PackageController@update')->middleware(["permission:packages screen"])->name('packages.update');
    Route::get('/packages/destroy', 'PricingListsControllers\PackageController@destroy')->middleware(["permission:packages screen"]);

    //pricinglist
    Route::get('/pricinglists', 'PricingListsControllers\PricingListController@index')->middleware(["permission:pricing lists screen"])->name('pricinglists.index');
    Route::get('/pricinglists/create', 'PricingListsControllers\PricingListController@create')->middleware(["permission:pricing lists screen"])->name('pricinglists.create');
    Route::post('/pricinglists/store', 'PricingListsControllers\PricingListController@store')->middleware(["permission:pricing lists screen"])->name('pricinglists.store');
    Route::get('/pricinglists/edit/{id}', 'PricingListsControllers\PricingListController@edit')->middleware(["permission:pricing lists screen"]);
    Route::post('/pricinglists/update', 'PricingListsControllers\PricingListController@update')->middleware(["permission:pricing lists screen"])->name('pricinglists.update');
    Route::get('/pricinglists/destroy', 'PricingListsControllers\PricingListController@destroy')->middleware(["permission:pricing lists screen"]);
    Route::get('/pricinglists/form', 'PricingListsControllers\PricingListController@getPricingListsForm')->middleware(["permission:pricing lists screen"])->name('pricinglists.form');
    Route::get('/pricinglists/form-all', 'PricingListsControllers\PricingListController@getPricingListsFormAll')->middleware(["permission:pricing lists screen"])->name('pricinglists.form-all');

    //priceofsale
    Route::get('/priceofsale', 'PricingListsControllers\PriceOfSaleController@index')->middleware(["permission:price of sale screen"])->name('priceofsale.index');
    Route::get('/priceofsale/create', 'PricingListsControllers\PriceOfSaleController@create')->middleware(["permission:price of sale screen"])->name('priceofsale.create');
    Route::post('/priceofsale/store', 'PricingListsControllers\PriceOfSaleController@store')->middleware(["permission:price of sale screen"])->name('priceofsale.store');
    Route::get('/priceofsale/price', 'PricingListsControllers\PriceOfSaleController@getPrice')->middleware(["permission:price of sale screen"])->name('priceofsale.price');
    Route::get('/priceofsale/edit/{id}', 'PricingListsControllers\PriceOfSaleController@edit')->middleware(["permission:price of sale screen"]);
    Route::post('/priceofsale/update', 'PricingListsControllers\PriceOfSaleController@update')->middleware(["permission:price of sale screen"])->name('priceofsale.update');
    Route::get('/priceofsale/destroy', 'PricingListsControllers\PriceOfSaleController@destroy')->middleware(["permission:price of sale screen"]);
    Route::get('/priceofsale/form', 'PricingListsControllers\PriceOfSaleController@getPriceOfSaleForm')->middleware(["permission:price of sale screen"])->name('priceofsale.form');

    //notifications
    Route::get('/notifications/requestRechargeNotifications','SettingsControllers\RequestRechargeNotificationController@index')->name('request-recharge-notification.index');
    Route::get('/notifications/requestRechargeNotifications/clearall', 'SettingsControllers\RequestRechargeNotificationController@clearAll')->middleware(["permission:notifications screen"])->name('request-recharge-notifications.clearall');
    Route::get('/notifications/requestRechargeNotifications/clearnotificationheader','SettingsControllers\RequestRechargeNotificationController@clearHeaderNotification')->name('request-recharge-notifications.clearnotificationheader');

    Route::get('/notifications/requestRechargeNotifications/clearnotification', 'SettingsControllers\RequestRechargeNotificationController@clearNotification')->name('request-recharge-notifications.clearnotification');
   
    Route::get('notifications', 'SettingsControllers\NotificationController@index')->middleware(["permission:notifications screen"])->name('notifications.index');
    Route::get('/notifications/clearall', 'SettingsControllers\NotificationController@clearAll')->middleware(["permission:notifications screen"])->name('notifications.clearall');
    Route::get('/notifications/clearnotification', 'SettingsControllers\NotificationController@clearNotification')->middleware(["permission:notifications screen"])->name('notifications.clearnotification');
    Route::get('/notifications/clearnotificationheader','SettingsControllers\NotificationController@clearHeaderNotification')->middleware(["permission:notifications screen"])->name('notifications.clearnotificationheader');

Route::get('notifications/quantitylimit','SettingsControllers\CardsQuantityLimitController@index')->middleware(["permission:notifications screen"])->name('quantitylimits.index');
Route::get('notifications/quantitylimit/create', 'SettingsControllers\CardsQuantityLimitController@create')->middleware(["permission:notifications screen"])->name('quantitylimits.create');
Route::post('notifications/quantitylimit/store', 'SettingsControllers\CardsQuantityLimitController@store')->middleware(["permission:notifications screen"])->name('quantitylimits.store');
Route::get('notifications/quantitylimit/form', 'SettingsControllers\CardsQuantityLimitController@getQuantityLimitForm')->middleware(["permission:notifications screen"])->name('quantitylimits.form');
Route::get('notifications/quantitylimit/destroy', 'SettingsControllers\CardsQuantityLimitController@destroy')->middleware(["permission:notifications screen"])->name('quantitylimits.destroy');
    

//pushnotifications
    Route::get('/notifications/pushnotifications', 'SettingsControllers\PushNotificationController@index')->middleware(["permission:notifications screen"])->name('pushnotifications.index');
    Route::post('/notifications/pushnotifications/store', 'SettingsControllers\PushNotificationController@store')->middleware(["permission:notifications screen"])->name('pushnotifications.store');



    //scannedCards
    Route::get('/scannedcards', 'SettingsControllers\ScannedCardsController@index')->name('scannedcards.index');
    Route::get('/scannedcards/create', 'SettingsControllers\ScannedCardsController@create')->name('scannedcards.create');
    Route::post('/scannedcards/store', 'SettingsControllers\ScannedCardsController@store')->name('scannedcards.store');
    Route::get('/scannedcards/start', 'SettingsControllers\ScannedCardsController@startScan')->name('scannedcards.start');
    Route::post('/scannedcards/clear', 'SettingsControllers\ScannedCardsController@clearData')->name('scannedcards.clear');
    Route::get('settings', 'SettingsControllers\SettingController@index')->middleware(["permission:settings screen"])->name('settings.index');
   //V_6 UPDATES 04/01/2022
    Route::get('settings/userbalancelimitnotification', 'SettingsControllers\SettingController@userBalanceLimitNotification')->middleware(["permission:settings screen"])->name('settings.userbalancelimitnotification');
//END V_6 UPDATES 04/01/2022
    Route::post('settings/store', 'SettingsControllers\SettingController@store')->middleware(["permission:settings screen"])->name('settings.store');
     //V_6 UPDATES 04/01/2022
    Route::post('settings/userbalancelimit/store', 'SettingsControllers\SettingController@userBalanceLimitStore')->middleware(["permission:settings screen"])->name('settings.userbalancelimit.store');
     //END V_6 UPDATES 04/01/2022
    //cardsLimit
    Route::get('/notifications/cardslimit', 'SettingsControllers\CardsLimitController@index')->middleware(["permission:notifications screen"])->name('cardslimit.index');
    Route::get('/notifications/cardslimit/create', 'SettingsControllers\CardsLimitController@create')->middleware(["permission:notifications screen"])->name('cardslimit.create');
    Route::post('/notifications/cardslimit/store', 'SettingsControllers\CardsLimitController@store')->middleware(["permission:notifications screen"])->middleware(["permission:card limits screen"])->name('cardslimit.store');
    Route::get('/notifications/cardslimit/edit/{id}', 'SettingsControllers\CardsLimitController@edit')->middleware(["permission:notifications screen"]);
    Route::post('/notifications/cardslimit/update', 'SettingsControllers\CardsLimitController@update')->middleware(["permission:notifications screen"])->name('cardslimit.update');
    Route::get('/notifications/cardslimit/destroy', 'SettingsControllers\CardsLimitController@destroy')->middleware(["permission:notifications screen"]);
    Route::get('/notifications/cardslimit/value', 'SettingsControllers\CardsLimitController@getValue')->middleware(["permission:notifications screen"])->name('cardslimit.value');
    Route::get('/notifications/cardslimit/form', 'SettingsControllers\CardsLimitController@getCardsLimitForm')->middleware(["permission:notifications screen"])->name('cardslimit.form');


    // cardexpiry

    Route::get('notifications/cardsexpiry', 'SettingsControllers\CardExpiryController@index')->middleware(["permission:notifications screen"])->name('cardsexpiry.index');
    Route::get('notifications/cardsexpiry/create', 'SettingsControllers\CardExpiryController@create')->middleware(["permission:notifications screen"])->name('cardsexpiry.create');
    Route::post('notifications/cardsexpiry/store', 'SettingsControllers\CardExpiryController@store')->middleware(["permission:notifications screen"])->middleware(["permission:card limits screen"])->name('cardsexpiry.store');

app/Models/SettingModels/Notification.php
<?php

namespace App\Models\SettingModels;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
class Notification extends Model
{
    
    use HasFactory,SoftDeletes;
    protected $fillable = ["title_en","title_ar","description_en","description_ar","is_seen","type","href",'is_delete_when_seen',"data","next_notification_at"];
    public function getCreatedAtAttribute($value)
    {
        return \Carbon\Carbon::parse($value)->format('d-m-Y H:i:s');
    }

}

app/Http/Controllers/AdminControllers/SettingsControllers/NotificationController.php
<?php

namespace App\Http\Controllers\AdminControllers\SettingsControllers;

use App\Facades\HelperFacade;
use App\Facades\ResponseWrapperFacade;
use App\Http\Controllers\Controller;
use App\ServicesInterface\NotificationsServiceInterface;
use Illuminate\Http\Request;

class NotificationController extends Controller
{

    private $_notificationsService;
    public function __construct(NotificationsServiceInterface $notificationsService)
    {
        $this->_notificationsService = $notificationsService;
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if(!HelperFacade::checkAdminPermission("Notifications")){
            return redirect()->back();
        }
        $notifications = $this->_notificationsService->latest();
        return view('admin.notifications.index', compact("notifications"));
    }

    public function clearAll()
    {

        if (request()->ajax()) {
            $this->_notificationsService->clearAll();
            return ResponseWrapperFacade::success();
        }
    }

    public function clearNotification(Request $request)
    {
        $notificationId = $request->notification_id;
        $this->_notificationsService->clearNotification($notificationId);
        return ResponseWrapperFacade::success();
    }
    
    public function clearHeaderNotification(Request $request){
        $notificationId = $request->notification_id;
   
        $notification  = $this->_notificationsService->findById($notificationId);
       
                $this->_notificationsService->clearNotification($notificationId);
        if (filter_var($notification->href, FILTER_VALIDATE_URL)) { 
            return ResponseWrapperFacade::successWithData(["href"=>$notification->href]);
          }

          $href = route('notifications.index');
          return ResponseWrapperFacade::successWithData(["href"=>$href]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/UserControllers/NotificationControllers/NotificationController.php
<?php

namespace App\Http\Controllers\UserControllers\NotificationControllers;

use App\Http\Controllers\Controller;
use App\ServicesInterface\NotificationsServiceInterface;
use Illuminate\Http\Request;

class NotificationController extends Controller
{

    private $_notificationService;
    public function __construct(NotificationsServiceInterface $notificationService)
    {
        $this->_notificationService = $notificationService;
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $this->_notificationService->updateUserNotification();
        
        $notifications = $this->_notificationService->userNotificationLatest($request->all());
       
       
        $notifications = $notifications['notifications'];
        
        return view('user.notifications.index',compact("notifications"));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/notifications/index.blade.php
{{-- V_5 UPDATES 26/12/2021 --}}
@extends('layouts.default')
@section('content')
<div class="content-wrapper">
    <div class="container" style="margin-top:100px;">
      <!-- Main content -->
      <section class="content">
          <div class="row">
            <div class="box">
				<div class="box-header with-border">
				  <h3 class="box-title">{{__('Notifications')}}</h3>
                </div>
                <div class="box-body">
                    <div class="col-12">
                        
                                <div class="table-responsive">
                                    <table  id="notificationDataTable" class="table  table-bordered table-hover display nowrap margin-top-10 w-p100">
                                  
                                        <thead>
                                            <tr>
                                            <th>{{__('#')}}</th>
                                            <th>{{__('Description En')}}</th>
                                          
                                                  <th>{{__('Description Ar')}}</th>
                                               
                                              <th>{{__('Status')}}</th>
                                            
                                              <th>{{__('Time')}}</th>
                                           
                                             
                                            </tr>
                                        </thead>
<tbody>
    @foreach($notifications as $key=>$notification)
    <tr @if($notification->is_cleared) style="background-color:#81C784" @else style="background-color:#E57373"  @endif class="cursor-pointer spaceUnder @if(!$notification->is_cleared) notification_read @endif" onclick="redirect('{{$notification->href}}','{{$notification->id}}','{{$notification->type}}')">										
            <td>
                <div style="color:white !important;" class="h-50 w-50 l-h-50 rounded text-center">
                {{++$key}}
                </div>
            </td>
            <td>
            <a href="javascript:void(0);" style="color:white !important;" class="text-dark font-weight-600 hover-primary font-size-16">{{$notification->title_en}}</a>
                <span style="color:white !important;" class="text-fade d-block">{{$notification->description_en}}</span>
            </td>
            <td style="direction: rtl">
                <a style="color:white !important;" href="javascript:void(0);" class="text-dark font-weight-600 hover-primary font-size-16">{{$notification->title_ar}}</a>
                    <span style="color:white !important;" class="text-fade d-block">{{$notification->description_ar}}</span>
                </td>
         <td>
             @if(!$notification->is_cleared)
         <span style="color:white !important;" class="badge badge-warning">{{__('UnSeen')}}</span>
         @else
         <span style="color:white !important;" class="badge badge-success">{{__('Seen')}}</span>
         @endif
         </td>
         <td><span style="color:white !important;" class="text-fade d-block">{{$notification->created_at}}</span></td>
     
        </tr>
     
    
     @endforeach
</tbody>
<tfoot>

    <tr>
        <th>{{__('#')}}</th>
        <th>{{__('Description En')}}</th>
      
              <th>{{__('Description Ar')}}</th>
           
          <th>{{__('Status')}}</th>
          <th>{{__('Time')}}</th>
      
        
       
         
        </tr>
</tfoot>

                                    </table>
                                    {{-- <table id="notificationDataTable" class="table no-border">
                                        <thead>
                                            <tr class="text-left">
                                                <th class="p-0" style="width: 50px"></th>
                                                <th class="p-0" style="min-width: 200px"></th>
                                                <th class="p-0" style="min-width: 150px"></th>
                                                <th class="p-0" style="min-width: 100px"></th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            @foreach($notifications as $key=>$notification)
                                        <tr class="cursor-pointer spaceUnder @if(!$notification->is_cleared) notification_read @endif" onclick="redirect('{{$notification->href}}','{{$notification->id}}','{{$notification->type}}')">										
                                                <td>
                                                    <div class="h-50 w-50 l-h-50 rounded text-center">
                                                    {{++$key}}
                                                    </div>
                                                </td>
                                                <td>
                                                <a href="javascript:void(0);" class="text-dark font-weight-600 hover-primary font-size-16">{{$notification->title_en}}</a>
                                                    <span class="text-fade d-block">{{$notification->description_en}}</span>
                                                </td>
                                                <td style="direction: rtl">
                                                    <a href="javascript:void(0);" class="text-dark font-weight-600 hover-primary font-size-16">{{$notification->title_ar}}</a>
                                                        <span class="text-fade d-block">{{$notification->description_ar}}</span>
                                                    </td>
                                             <td>
                                                 @if(!$notification->is_cleared)
                                             <span class="badge badge-warning">{{__('UnSeen')}}</span>
                                             @else
                                             <span class="badge badge-success">{{__('Seen')}}</span>
                                             @endif
                                             </td>
                                              
                                            </tr>
                                            <tr><td></td><td></td></tr>
                                        
                                         @endforeach
                                     
                                         
                                        </tbody>
                                    </table> --}}
                                </div>
                        
                    </div>
                </div>
            </div>
          </div>
      </section>
    </div>
</div>

<script>
    $(function(){
        $("#notificationDataTable").DataTable({ "pageLength":150,
            "lengthMenu": [[100, 150, 200, -1], [100, 150, 200, "All"]],})
    })
    function redirect(href,notificationId,notificationType){
   
        $.ajax({
            url:"{{route('notifications.clearnotification')}}",
            type:"GET",
            data:{notification_id:notificationId},
            dataType:"json",
            success:function(response){
if(response.status == CONSTANTS.SUCCESS){
    location.href = href;
}
            }
        })
      
    }
    </script>
@stop

{{-- END V_5 UPDATES 26/12/2021 --}}